global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using static System.Console;
global using FilesTransferApp.Core.Interfaces;
global using System.IO;
global using  FilesTransferApp.Infrastructure.Exts;
global using System.Collections.Concurrent;
